### ISSUE TITLE
how to apply authentication only on resolvers that require authentication and not to all resolvers

### ISSUE THREAD

**Issue by francelwebdev** [geek/graphi#35]
Hello Sir, when applying an authentication strategy (for example jwt) to the option: authStrategy this means that no graphql request can be made if there is no authentication token sent. Since some graphql resolvers will require authentication and not others, my question is how to apply authentication only on resolvers that require authentication and not to all resolvers. thanks

**Comment by geek** [comment]
@francelwebdev in that scenario it might make sense to have separate graphql endpoints, one that requires auth and another that doesn't. Another possibility is to combine them and then enforce the authentication rules within the resolver functions themselves, erroring when missing the required token. This is one of the reasons why I created graphi, so that the custom resolvers have access to the full request object where you can inspect the headers.
